/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bot.Healer;
import client.Spells;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import settings.UserSettings;

/**
 *
 * @author Radek
 */
public class HealingFrame extends javax.swing.JDialog {

    public Healer healer;
    private static HealingFrame _instance;
    public DefaultComboBoxModel spellsModel = new DefaultComboBoxModel();

    /**
     * Creates new form HealingFrame
     */
    public HealingFrame() {
        super(MainFrame.getInstance());
        
        _instance = this;
        
        initComponents();
        setLocationRelativeTo(null);
        init();
        
        new Thread(new Runnable() {

            @Override
            public void run() {
                while(true) {
                    if(HealingFrame.getInstance().isVisible()) {
                    HealingFrame.getInstance().updatePotionsLeft(Healer.visibleHpots(hppotType.getSelectedIndex()),
                            Healer.visibleMpots(mppotType.getSelectedIndex()));
                    }
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(HealingFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    public static HealingFrame getInstance() {
        return _instance;
    }

    private void init() {
        //Init the spellsModel.
        for (String s : Spells.getSpellNames()) {
            spellsModel.addElement(s);
        }
        spellCombo.setSelectedIndex(0);

        unpackSettings();
    }

    /**
     * Translates UserSettings.Healing into this frame.
     */
    public void packSettings() {
        UserSettings.Healing stg = MainFrame.getInstance().settings.healing;
        stg.spellName = spellCombo.getSelectedItem().toString();
        stg.spellHealth = UserSettings.Percentable.parse(spellHealth.getText());
        stg.spellMana = UserSettings.Percentable.parse(spellMana.getText());
        stg.hpPotHealth = UserSettings.Percentable.parse(hppotHealth.getText());
        stg.hpPotType = hppotType.getSelectedIndex();
        stg.mpPotMana = UserSettings.Percentable.parse(mppotMana.getText());
        stg.mpPotType = (int) mppotType.getSelectedIndex();
    }

    /**
     * Translates this frame into UserSettings.Healing.
     */
    public void unpackSettings() {
        UserSettings.Healing set = MainFrame.getInstance().settings.healing;
        spellCombo.setSelectedItem(set.spellName);
        spellHealth.setText(set.spellHealth.toString());
        spellMana.setText(set.spellMana.toString());
        hppotHealth.setText(set.hpPotHealth.toString());
        hppotType.setSelectedItem(set.hpPotType);
        mppotMana.setText(set.mpPotMana.toString());
        mppotType.setSelectedItem(set.mpPotType);
    }
    
    public void updatePotionsLeft(int health, int mana) {
        potionsLeftLabel.setText(health + " health potions left, " + mana + " mana potions left");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hppotType = new javax.swing.JComboBox();
        mppotType = new javax.swing.JComboBox();
        spellCombo = new javax.swing.JComboBox();
        enableButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        spellHealth = new javax.swing.JTextField();
        spellMana = new javax.swing.JTextField();
        hppotHealth = new javax.swing.JTextField();
        mppotMana = new javax.swing.JTextField();
        potionsLeftLabel = new javax.swing.JLabel();

        setTitle("Healing");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setText("Spell:");

        jLabel2.setText("HP Potion:");

        jLabel3.setText("MP Potion:");

        jLabel5.setText("Health");

        jLabel6.setText("Health");

        jLabel7.setText("Mana");

        jLabel8.setText("Mana");

        jLabel9.setText("Type");

        jLabel10.setText("Type");

        hppotType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ampoule", "Vial", "Shot", "Jar", "Flask" }));

        mppotType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ampoule", "Vial", "Shot", "Jar", "Flask" }));

        spellCombo.setModel(spellsModel);

        enableButton.setText("Enable");
        enableButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enableButtonMouseClicked(evt);
            }
        });

        spellHealth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        spellHealth.setText("0");

        spellMana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        spellMana.setText("0");

        hppotHealth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hppotHealth.setText("0");

        mppotMana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mppotMana.setText("0");

        potionsLeftLabel.setText("30 mana potions left, 20 health potions left");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spellCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spellHealth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hppotHealth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mppotMana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hppotType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spellMana, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mppotType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(potionsLeftLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enableButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(spellCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spellHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spellMana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(hppotType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hppotHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(mppotType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mppotMana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enableButton)
                    .addComponent(potionsLeftLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enableButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enableButtonMouseClicked
        packSettings();
        if (enableButton.getText().contains("Enable")) {
            enableButton.setText("Disable");
            healer = new Healer(MainFrame.getInstance().settings.healing);
            healer.start();
        } else {
            enableButton.setText("Enable");
            healer.interrupt();
            healer = null;
        }
        // TODO: start the healer.
    }//GEN-LAST:event_enableButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enableButton;
    private javax.swing.JTextField hppotHealth;
    private javax.swing.JComboBox hppotType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mppotMana;
    private javax.swing.JComboBox mppotType;
    private javax.swing.JLabel potionsLeftLabel;
    private javax.swing.JComboBox spellCombo;
    private javax.swing.JTextField spellHealth;
    private javax.swing.JTextField spellMana;
    // End of variables declaration//GEN-END:variables
}
