/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import client.Client;
import client.Container;
import client.Slots;
import java.awt.Component;
import java.awt.event.HierarchyEvent;

/**
 *
 * @author Moshe Revah
 */
public class InventoryPanel extends javax.swing.JPanel {

    private static InventoryPanel instance;

    /**
     * Creates new form InventoryPanel
     */
    public InventoryPanel() {
        instance = this;
        initComponents();

        containersPanel.setSize(182, 40);
        containersPanel.setLayout(new WrapLayout(WrapLayout.LEFT, 0, 0));
    }

    public void openContainer(Container cont) {
        containersPanel.add(new JContainer(cont));

        MainFrame.getInstance().pack();
        repaint();
    }

    public void closeContainer(Container cont) {
        int n = containersPanel.getComponentCount();
        for (int i = 0; i < n; i++) {
            if (containersPanel.getComponent(i) instanceof JContainer) {
                JContainer jcont = (JContainer) containersPanel.getComponent(i);
                if (jcont.getContainer().id == cont.id) {
                    containersPanel.remove(i);
                    break;
                }
            }
        }

        MainFrame.getInstance().pack();
        repaint();
    }

    public void updateContainer(Container cont) {
        for (Component comp : containersPanel.getComponents()) {
            if (comp instanceof JContainer) {
                JContainer jcont = (JContainer) comp;
                if (jcont.getContainer().id == cont.id) {
                    jcont.wrap(cont);
                    break;
                }
            }
        }

        MainFrame.getInstance().pack();
        repaint();
    }

    public static InventoryPanel getInstance() {
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        containersPanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inventory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(208, 381));

        jScrollPane1.setBorder(null);

        javax.swing.GroupLayout containersPanelLayout = new javax.swing.GroupLayout(containersPanel);
        containersPanel.setLayout(containersPanelLayout);
        containersPanelLayout.setHorizontalGroup(
            containersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        containersPanelLayout.setVerticalGroup(
            containersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(containersPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containersPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
