/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginFrame.java
 *
 * Created on 2012-01-25, 14:16:24
 */
package gui;

import bot.Bot;
import bot.GfxFilter;
import client.Client;
import client.networking.PacketReceiver;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import settings.Constants;

/**
 * Login frame.
 *
 * @author Myzreal
 */
public class LoginFrame extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(PacketReceiver.class.getName());
    private static LoginFrame _instance;
    private structures.Character[] chars;
    private DefaultListModel listModel = new DefaultListModel();
    private GfxFilter fileFilter = new GfxFilter();
    
    private String username, password;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        _instance = this;
        initComponents();
        setLocationRelativeTo(null);
        init();
        setVisible(true);
        
        jTabbedPane1.setEnabledAt(1, false);
        emailArea.requestFocusInWindow();
    }

    public static LoginFrame getInstance() {
        return _instance;
    }
    
    private void init() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseCharacterFrame = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        charList = new javax.swing.JList();
        charChoiceButton = new javax.swing.JButton();
        fileChooser = new javax.swing.JFileChooser();
        okayDialog = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        okayButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        botAccPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        emailArea = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordArea = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        zezAccPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rememberedCharList = new javax.swing.JList();
        selectButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        zezUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        zezPassword = new javax.swing.JPasswordField();
        zezLogin = new javax.swing.JButton();

        chooseCharacterFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        chooseCharacterFrame.setTitle("Choose character");
        chooseCharacterFrame.setMinimumSize(new java.awt.Dimension(380, 270));
        chooseCharacterFrame.setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Characters"));

        charList.setModel(listModel);
        charList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        charList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                handleKeyReleasedOnList(evt);
            }
        });
        jScrollPane1.setViewportView(charList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        charChoiceButton.setText("Choose");
        charChoiceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                handleCharacterChosen(evt);
            }
        });

        javax.swing.GroupLayout chooseCharacterFrameLayout = new javax.swing.GroupLayout(chooseCharacterFrame.getContentPane());
        chooseCharacterFrame.getContentPane().setLayout(chooseCharacterFrameLayout);
        chooseCharacterFrameLayout.setHorizontalGroup(
            chooseCharacterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseCharacterFrameLayout.createSequentialGroup()
                .addGroup(chooseCharacterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chooseCharacterFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(chooseCharacterFrameLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(charChoiceButton)))
                .addContainerGap())
        );
        chooseCharacterFrameLayout.setVerticalGroup(
            chooseCharacterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseCharacterFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(charChoiceButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setDialogTitle("Path to Zezenia.gfx");
        fileChooser.setFileFilter(fileFilter);

        okayDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        okayDialog.setTitle("Error");
        okayDialog.setAlwaysOnTop(true);
        okayDialog.setIconImage(null);
        okayDialog.setMinimumSize(new java.awt.Dimension(320, 190));
        okayDialog.setName("Error!");
        okayDialog.setResizable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Zezenia.gfx file specified is incorrect.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Bot will work without it, but there will be no images :(");

        okayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/okay-face.jpg"))); // NOI18N
        okayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                handleOkayPressed(evt);
            }
        });

        javax.swing.GroupLayout okayDialogLayout = new javax.swing.GroupLayout(okayDialog.getContentPane());
        okayDialog.getContentPane().setLayout(okayDialogLayout);
        okayDialogLayout.setHorizontalGroup(
            okayDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(okayDialogLayout.createSequentialGroup()
                .addGroup(okayDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(okayDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(okayDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(okayDialogLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel5))))
                    .addGroup(okayDialogLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(okayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        okayDialogLayout.setVerticalGroup(
            okayDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(okayDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(okayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login to ZenBot");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ZenBot");

        jTabbedPane1.setToolTipText("");

        jLabel3.setText("Email:");

        emailArea.setNextFocusableComponent(passwordArea);
        emailArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailAreaKeyPressed(evt);
            }
        });

        jLabel4.setText("Password:");

        passwordArea.setNextFocusableComponent(emailArea);
        passwordArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordAreaKeyPressed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                handleLoginPressed(evt);
            }
        });

        jLabel8.setText("<html>Type in the email and password you used at <a href=\"http://google.com/\">ZenBot.net</a>");

        javax.swing.GroupLayout botAccPanelLayout = new javax.swing.GroupLayout(botAccPanel);
        botAccPanel.setLayout(botAccPanelLayout);
        botAccPanelLayout.setHorizontalGroup(
            botAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botAccPanelLayout.createSequentialGroup()
                .addGroup(botAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(botAccPanelLayout.createSequentialGroup()
                        .addGroup(botAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(botAccPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4))
                            .addGroup(botAccPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(botAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailArea)
                            .addComponent(passwordArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginButton))
                    .addGroup(botAccPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        botAccPanelLayout.setVerticalGroup(
            botAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botAccPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(botAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(botAccPanelLayout.createSequentialGroup()
                        .addGroup(botAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(botAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bot login", botAccPanel);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("History"));

        rememberedCharList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(rememberedCharList);

        selectButton.setText("Login");
        selectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                selectCharPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(selectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Login with another character"));

        jLabel2.setText("Username:");

        zezUsername.setNextFocusableComponent(zezPassword);
        zezUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                zezUsernameKeyPressed(evt);
            }
        });

        jLabel7.setText("Password:");

        zezPassword.setNextFocusableComponent(zezUsername);
        zezPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                zezPasswordKeyPressed(evt);
            }
        });

        zezLogin.setText("Login");
        zezLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                handleZezLoginPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zezUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(zezPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zezLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(zezLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(zezUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(zezPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout zezAccPanelLayout = new javax.swing.GroupLayout(zezAccPanel);
        zezAccPanel.setLayout(zezAccPanelLayout);
        zezAccPanelLayout.setHorizontalGroup(
            zezAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zezAccPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zezAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        zezAccPanelLayout.setVerticalGroup(
            zezAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zezAccPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Zezenia login", zezAccPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleCharacterChosen(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handleCharacterChosen
        //Login to the game.
        String[] tempp = charList.getSelectedValue().toString().split("\\|");
        String chosenChar = tempp[0].trim();
        //Safety check.
        if (chosenChar.isEmpty()) {
            return;
        }

        logger.log(Level.INFO, "logging in with {0}", chosenChar);
        structures.Character finalChar = getCharacterByName(chosenChar);
        if (finalChar != null) {
            try {
                Client.getInstance().login(username, password, finalChar);
                chooseCharacterFrame.setVisible(false);
            } catch (Exception ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_handleCharacterChosen

    private void handleLoginPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handleLoginPressed
        //TODO: Perform a login to bot accounting system once it is done.
        //Following code should be executed ONLY IF LOGIN TO BOT ACCOUNT WAS SUCCESFUL.
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setSelectedIndex(1);
        zezUsername.requestFocusInWindow();
    }//GEN-LAST:event_handleLoginPressed

    private void handleKeyReleasedOnList(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_handleKeyReleasedOnList
        if (evt.getKeyCode() == evt.VK_ENTER) {
            handleCharacterChosen(null);
        }
    }//GEN-LAST:event_handleKeyReleasedOnList

    private void handleOkayPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handleOkayPressed
        okayDialog.dispose();
        setVisible(true);
    }//GEN-LAST:event_handleOkayPressed

    private void handleZezLoginPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handleZezLoginPressed
        //TODO: Add an additional check if here if player is really logged in to a proper bot account.
        username = zezUsername.getText().trim();
        password = new String(zezPassword.getPassword()).trim();

        //Safety check.
        if (username.isEmpty() || password.isEmpty()) {
            return;
        }

        zezUsername.setText("");
        zezPassword.setText("");

        try {
            chars = Client.getCharList(username, password);
        } catch (Exception ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (chars != null) {
            //Show the character selection screen.
            for (structures.Character c : chars) {
                listModel.addElement(c.name + " | " + c.vocation + " | lv." + c.level + " | " + c.worldName);
            }
            charList.setSelectedIndex(0);
            chooseCharacterFrame.setVisible(true);
        }
    }//GEN-LAST:event_handleZezLoginPressed

    private void selectCharPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectCharPressed
        // TODO: the user chose a remembered character from the list. Perform a login directly to that character.
        try {
            //Client.getInstance().login("XXX", "XXX", new structures.Character("XXX", null, "tipitaka.zezeniaonline.com", null, null, (short) 0));
        } catch (Exception ex) {
            Logger.getLogger(Bot.class.getName()).log(Level.SEVERE, null, ex); }
    }//GEN-LAST:event_selectCharPressed

    private void zezUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zezUsernameKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            handleZezLoginPressed(null);
        }
    }//GEN-LAST:event_zezUsernameKeyPressed

    private void zezPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zezPasswordKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            handleZezLoginPressed(null);
        }
    }//GEN-LAST:event_zezPasswordKeyPressed

    private void emailAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailAreaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            handleLoginPressed(null);
        }
    }//GEN-LAST:event_emailAreaKeyPressed

    private void passwordAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordAreaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            handleLoginPressed(null);
        }
    }//GEN-LAST:event_passwordAreaKeyPressed

    private structures.Character getCharacterByName(String name) {
        if (chars != null) {
            for (structures.Character c : chars) {
                if (c.name.equals(name)) {
                    return c;
                }
            }
        }

        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botAccPanel;
    private javax.swing.JButton charChoiceButton;
    private javax.swing.JList charList;
    private javax.swing.JFrame chooseCharacterFrame;
    private javax.swing.JTextField emailArea;
    public javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton okayButton;
    public javax.swing.JDialog okayDialog;
    private javax.swing.JPasswordField passwordArea;
    private javax.swing.JList rememberedCharList;
    private javax.swing.JButton selectButton;
    private javax.swing.JPanel zezAccPanel;
    private javax.swing.JButton zezLogin;
    private javax.swing.JPasswordField zezPassword;
    private javax.swing.JTextField zezUsername;
    // End of variables declaration//GEN-END:variables
}
