/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import structures.Status;

/**
 *
 * @author Moshe Revah
 */
public class PlayerStatusPanel extends javax.swing.JPanel {

    private static PlayerStatusPanel instance;
    
    /**
     * Creates new form PlayerStatusPanel
     */
    public PlayerStatusPanel() {
        instance = this;
        initComponents();
    }
    
    public void update(Status s) {
        //Status section
        healthLabel.setText(s.hp + "/" + s.maxHp);
        hpBar.setMaximum(s.maxHp);
        hpBar.setValue(s.hp);
        hpBar.setToolTipText(String.valueOf((int) (hpBar.getPercentComplete() * 100)) + "%");
        manaLabel.setText(s.mp + "/" + s.maxMp);
        mpBar.setMaximum(s.maxMp);
        mpBar.setValue(s.mp);
        mpBar.setToolTipText(String.valueOf((int) (mpBar.getPercentComplete() * 100)) + "%");

        //Experience section
        levelLabel.setText(String.valueOf(s.level));
        expLabel.setText(String.valueOf(s.exp));
        expBar.setValue(s.expPercent);
        expBar.setToolTipText(String.valueOf((int) (expBar.getPercentComplete() * 100)) + "%");

        //Statistics
        magicLevelLabel.setText(String.valueOf(s.magicLevel) + (s.magicLevelBonus > 0 ? " +" + String.valueOf(s.magicLevelBonus) : ""));
        magicLevelBar.setValue(s.magicLevelPercent);
        magicLevelBar.setToolTipText(String.valueOf((int) (magicLevelBar.getPercentComplete() * 100)) + "%");
        
        mLabel.setText(String.valueOf(s.melee) + (s.meleeBonus > 0 ? " +" + String.valueOf(s.meleeBonus) : ""));
        meleeBar.setValue(s.meleePercent);
        meleeBar.setToolTipText(String.valueOf((int) (meleeBar.getPercentComplete() * 100)) + "%");
        
        distLabel.setText(String.valueOf(s.distance) + (s.distanceBonus > 0 ? " +" + String.valueOf(s.distanceBonus) : ""));
        distanceBar.setValue(s.distancePercent);
        distanceBar.setToolTipText(String.valueOf((int) (distanceBar.getPercentComplete() * 100)) + "%");
        
        defLabel.setText(String.valueOf(s.defense) + (s.defenseBonus > 0 ? " +" + String.valueOf(s.defenseBonus) : ""));
        defenseBar.setValue(s.defensePercent);
        defenseBar.setToolTipText(String.valueOf((int) (defenseBar.getPercentComplete() * 100)) + "%");
    }
    
    public static PlayerStatusPanel getInstance() {
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        healthLabel = new javax.swing.JLabel();
        manaLabel = new javax.swing.JLabel();
        magicLevelLabel = new javax.swing.JLabel();
        magicLevelBar = new javax.swing.JProgressBar();
        mpBar = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        expLabel = new javax.swing.JLabel();
        mLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hpBar = new javax.swing.JProgressBar();
        meleeBar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        expBar = new javax.swing.JProgressBar();
        levelLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        defenseBar = new javax.swing.JProgressBar();
        defLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        distanceBar = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        distLabel = new javax.swing.JLabel();

        jScrollPane1.setPreferredSize(new java.awt.Dimension(178, 412));

        setBorder(javax.swing.BorderFactory.createTitledBorder("Character status"));

        jScrollPane2.setBorder(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(168, 306));

        healthLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        healthLabel.setText("0");

        manaLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        manaLabel.setText("0");

        magicLevelLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        magicLevelLabel.setText("0");

        magicLevelBar.setBackground(new java.awt.Color(0, 0, 0));
        magicLevelBar.setForeground(new java.awt.Color(0, 204, 0));
        magicLevelBar.setPreferredSize(new java.awt.Dimension(146, 10));

        mpBar.setBackground(new java.awt.Color(0, 0, 0));
        mpBar.setForeground(new java.awt.Color(0, 0, 255));
        mpBar.setPreferredSize(new java.awt.Dimension(146, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Melee");

        expLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        expLabel.setText("0");

        mLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mLabel.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Health");

        hpBar.setBackground(new java.awt.Color(0, 0, 0));
        hpBar.setForeground(new java.awt.Color(255, 0, 51));
        hpBar.setMaximumSize(new java.awt.Dimension(32767, 14));
        hpBar.setMinimumSize(new java.awt.Dimension(10, 14));
        hpBar.setPreferredSize(new java.awt.Dimension(146, 10));

        meleeBar.setBackground(new java.awt.Color(0, 0, 0));
        meleeBar.setForeground(new java.awt.Color(0, 204, 0));
        meleeBar.setPreferredSize(new java.awt.Dimension(146, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Experience");

        expBar.setBackground(new java.awt.Color(0, 0, 0));
        expBar.setForeground(new java.awt.Color(204, 0, 255));
        expBar.setPreferredSize(new java.awt.Dimension(146, 10));

        levelLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        levelLabel.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Level");

        defenseBar.setBackground(new java.awt.Color(0, 0, 0));
        defenseBar.setForeground(new java.awt.Color(0, 204, 0));
        defenseBar.setToolTipText("");
        defenseBar.setPreferredSize(new java.awt.Dimension(146, 10));

        defLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        defLabel.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mana");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Defense");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Magic level");

        distanceBar.setBackground(new java.awt.Color(0, 0, 0));
        distanceBar.setForeground(new java.awt.Color(0, 204, 0));
        distanceBar.setPreferredSize(new java.awt.Dimension(146, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Distance");

        distLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        distLabel.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mLabel))
                    .addComponent(defenseBar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(distanceBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meleeBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hpBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mpBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(expBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(healthLabel))
                    .addComponent(magicLevelBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manaLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(distLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(defLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(magicLevelLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(levelLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(healthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hpBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(manaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(levelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(expLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(magicLevelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(magicLevelBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meleeBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(distLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(distanceBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(defLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(defenseBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel defLabel;
    private javax.swing.JProgressBar defenseBar;
    private javax.swing.JLabel distLabel;
    private javax.swing.JProgressBar distanceBar;
    private javax.swing.JProgressBar expBar;
    private javax.swing.JLabel expLabel;
    private javax.swing.JLabel healthLabel;
    private javax.swing.JProgressBar hpBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel mLabel;
    private javax.swing.JProgressBar magicLevelBar;
    private javax.swing.JLabel magicLevelLabel;
    private javax.swing.JLabel manaLabel;
    private javax.swing.JProgressBar meleeBar;
    private javax.swing.JProgressBar mpBar;
    // End of variables declaration//GEN-END:variables
}
